Controllers do not stop interacting after a touch condition
Innoactive/XR-Interaction-Component pull request #62
Opened 2020-09-14 07:43 UTC by Gusinuhe

### Description

**Fixes**: If after a touch condition there is a disabled behavior that disables the same object that was previously touched, the controller that touched the object stops interacting (no more touch or grab), this can be reverted after the user uses that controller for teleporting or to show the UI ray controller.

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Make a course where you have to touch something, the next step right after the touch condition, disable the very same object (like in CKD when the user has to touch the button on the screen), then try to touch or grab another object.

### Known issues

If the same procedure is also applied for a grab condition, the controller also gets disabled. That is another issue that will have its own ticket.

2020-09-15 21:04 UTC, aleksei-korolev requested changes

2020-09-15 21:04 UTC, aleksei-korolev commented on Editor/Properties/SnappablePropertyEditor.cs
> -    public class SnappablePropertyEditor : Editor
API break, use [Obsolete] instead.

2020-09-15 21:04 UTC, aleksei-korolev commented on Runtime/Interaction/InteractableObject.cs
> +            bool wasTouchable = isTouchable, wasGrabbable = isGrabbable, wasUsable = isUsable;
Please, break it into three separate declarations.

2020-09-16 09:46 UTC, tomwim approved these changes
What @aleksei-korolev said, I would also like to be changed.

Otherwise I tested it in VR and it solves the issue. What a subtle but nice fix 👍

2020-09-16 09:58 UTC, Maxsiom approved these changes
Tested and worked for me as well. But I would also like to see Aleksei's changes. 👍

2020-09-17 12:51 UTC, Gusinuhe commented
The changes are not really that straightforward forward and there are still edge cases were that were not considered yet.
Due to a sensitive time for releasing, requested changes will be addressed in a future PR.

2020-09-17 17:04 UTC, merged