Feature/dynamically loaded xr rigs
Innoactive/XR-Interaction-Component pull request #79
Opened 2021-01-26 09:52 UTC by SimonTheSourcerer

### Description

2021-01-26 16:02 UTC, Gusinuhe requested changes

2021-01-26 16:22 UTC, SimonTheSourcerer commented on Editor/Rigs/XRSimulatorSetup.cs
> +            return IsEventManagerInScene() == false && PlayerSettings.virtualRealitySupported == false;
I have not seen anything from the XR Plugin Management preventing me to start the simulator

2021-01-27 10:27 UTC, Gusinuhe commented on Runtime/Rigs/XRSetupBase.cs
> +    public abstract class XRSetupBase : InteractionRigProvider
Missing docs

2021-01-27 14:47 UTC, Gusinuhe commented
Rigs are not instantiated and the following error is produced: 

![image](https://user-images.githubusercontent.com/6911992/106007809-f70beb80-60b6-11eb-8050-8250899717f0.png)

2021-01-27 15:01 UTC, Gusinuhe commented on Editor/XRInteractionSceneSetup.cs
> +                Debug.Log("TEST");
TEST!!

2021-01-27 15:33 UTC, Gusinuhe approved these changes

2021-02-01 10:57 UTC, Gusinuhe approved these changes

2021-02-01 11:04 UTC, SimonTheSourcerer commented
/azp run

2021-02-01 11:22 UTC, merged