fix: make sure xr is loaded on scene load
Innoactive/XR-Interaction-Component pull request #98
Opened 2021-04-08 15:16 UTC by tomwim

### Description
Makes sure Unity XR is properly initialized on scene load / rig setup

Related PRs:
https://github.com/Innoactive/Basic-Interaction-Component/pull/49

2021-04-12 12:17 UTC, Gusinuhe requested changes

2021-04-12 12:17 UTC, Gusinuhe commented on Runtime/Rigs/XRSetupBase.cs
> +            }
This fails if the `XR Management Plugin is not installed` (could be the case if the user has the legacy VR support enabled for OpenVR).

2021-04-12 12:17 UTC, Gusinuhe commented on Runtime/Rigs/XRSetupBase.cs
> +            }
Additionally, this does not address the same issue for (the legacy) OpenVR.

2021-04-14 09:03 UTC, tomwim commented
Closed

2021-04-14 09:03 UTC, closed without merging